// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU88C5WUXOsx5z-mnrlz7Go25061ORRKA',
    appId: '1:1047327723976:web:04b0c5c5187002e5faf0fd',
    messagingSenderId: '1047327723976',
    projectId: 'trainxercise',
    authDomain: 'trainxercise.firebaseapp.com',
    storageBucket: 'trainxercise.appspot.com',
    measurementId: 'G-3W0S4B3W3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUn1wpdTTEwgZqcTTrCEGdPWbX3CibKYg',
    appId: '1:1047327723976:android:1cd93b8538d91f4ffaf0fd',
    messagingSenderId: '1047327723976',
    projectId: 'trainxercise',
    storageBucket: 'trainxercise.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8sa-7ty681rMJH4ntu6alr9KK53dRFEc',
    appId: '1:1047327723976:ios:98fc0f82450ea05afaf0fd',
    messagingSenderId: '1047327723976',
    projectId: 'trainxercise',
    storageBucket: 'trainxercise.appspot.com',
    iosClientId: '1047327723976-kv6nkqlmarge51sif5g81fa1qs9gi607.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainxercise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8sa-7ty681rMJH4ntu6alr9KK53dRFEc',
    appId: '1:1047327723976:ios:98fc0f82450ea05afaf0fd',
    messagingSenderId: '1047327723976',
    projectId: 'trainxercise',
    storageBucket: 'trainxercise.appspot.com',
    iosClientId: '1047327723976-kv6nkqlmarge51sif5g81fa1qs9gi607.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainxercise',
  );
}
